services:
  server:
    build:
      context: .
      dockerfile: Dockerfile5
    image: test:local
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
